# Generated by Django 2.2 on 2020-09-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email',
        ),
    ]
