# Generated by Django 2.2 on 2020-09-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0002_remove_player_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rations',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
