# Generated by Django 2.2 on 2020-09-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninja_app', '0003_player_rations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rations',
        ),
    ]
